// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ueeauGl-xNMOEusTrLery-2NroNsUuc',
    appId: '1:553618624255:web:53e7a4bfe9612721d486ca',
    messagingSenderId: '553618624255',
    projectId: 'projeto-moviedex',
    authDomain: 'projeto-moviedex.firebaseapp.com',
    storageBucket: 'projeto-moviedex.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJAvuDviIwQp6gtjgNI6vAhqZ8UbcPQ_E',
    appId: '1:553618624255:android:3595a16154762f7cd486ca',
    messagingSenderId: '553618624255',
    projectId: 'projeto-moviedex',
    storageBucket: 'projeto-moviedex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWAr6YKzjg6oJFOm10Uh5zprbml8dLlO4',
    appId: '1:553618624255:ios:b9d9ec31a600f821d486ca',
    messagingSenderId: '553618624255',
    projectId: 'projeto-moviedex',
    storageBucket: 'projeto-moviedex.firebasestorage.app',
    iosBundleId: 'com.example.projetomobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWAr6YKzjg6oJFOm10Uh5zprbml8dLlO4',
    appId: '1:553618624255:ios:b9d9ec31a600f821d486ca',
    messagingSenderId: '553618624255',
    projectId: 'projeto-moviedex',
    storageBucket: 'projeto-moviedex.firebasestorage.app',
    iosBundleId: 'com.example.projetomobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4ueeauGl-xNMOEusTrLery-2NroNsUuc',
    appId: '1:553618624255:web:3bb7379e5569bc79d486ca',
    messagingSenderId: '553618624255',
    projectId: 'projeto-moviedex',
    authDomain: 'projeto-moviedex.firebaseapp.com',
    storageBucket: 'projeto-moviedex.firebasestorage.app',
  );
}
